@HabitTrackerApi_HostAddress = http://localhost:5213

### Health check
GET {{HabitTrackerApi_HostAddress}}/health
Accept: application/json

###

### Register
POST {{HabitTrackerApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123",
  "confirmPassword": "test123"
}

###

### Login
POST {{HabitTrackerApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123"
}

###

### Alışkanlıkları getir (Bearer token gerektirir)
GET {{HabitTrackerApi_HostAddress}}/api/habits?page=1&pageSize=50
Accept: application/json
Authorization: Bearer {{token}}

###