CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" character varying(100),
    "AvatarUrl" character varying(2048),
    "CreatedAt" timestamp with time zone NOT NULL,
    "TotalXp" integer NOT NULL,
    "TimeZoneId" character varying(100) NOT NULL DEFAULT 'Europe/Istanbul',
    "EquippedBackground" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "Badges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Badges" PRIMARY KEY ("Id")
);


CREATE TABLE "EmailOutboxItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ToEmail" text NOT NULL,
    "Subject" text NOT NULL,
    "Body" text NOT NULL,
    "Status" integer NOT NULL,
    "AttemptCount" integer NOT NULL,
    "LastError" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "NextAttemptAt" timestamp with time zone,
    "SentAt" timestamp with time zone,
    "LockedAt" timestamp with time zone,
    "LockedBy" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_EmailOutboxItems" PRIMARY KEY ("Id")
);


CREATE TABLE "PushOutboxItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "Status" integer NOT NULL,
    "AttemptCount" integer NOT NULL,
    "LastError" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "NextAttemptAt" timestamp with time zone,
    "SentAt" timestamp with time zone,
    "LockedAt" timestamp with time zone,
    "LockedBy" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_PushOutboxItems" PRIMARY KEY ("Id")
);


CREATE TABLE "RecalculationOutboxItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "JobType" integer NOT NULL,
    "HabitId" integer,
    "BookId" integer,
    "UserId" text NOT NULL,
    "TimeZoneId" text,
    "Status" integer NOT NULL,
    "AttemptCount" integer NOT NULL,
    "LastError" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "NextAttemptAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "LockedAt" timestamp with time zone,
    "LockedBy" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_RecalculationOutboxItems" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "NormalizedTitle" text NOT NULL,
    "ClientRequestId" character varying(100),
    "Author" character varying(200),
    "GoalType" integer NOT NULL,
    "Period" integer NOT NULL,
    "TotalPages" integer,
    "DailyGoalAmount" integer NOT NULL,
    "CurrentPage" integer NOT NULL,
    "TotalMinutesRead" integer NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "ManuallyCompleted" boolean NOT NULL,
    "CompletionBonusAwarded" boolean NOT NULL,
    "IsArchived" boolean NOT NULL,
    "ArchivedAt" timestamp with time zone,
    "Notes" character varying(1000),
    "CoverImageUrl" character varying(2048),
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "DeviceTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Token" character varying(500) NOT NULL,
    "Platform" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastSeenAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_DeviceTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeviceTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Flowers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "WaterAmount" integer NOT NULL,
    "Level" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_Flowers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Flowers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Habits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "NormalizedName" text NOT NULL,
    "ClientRequestId" character varying(100),
    "DailyGoal" integer NOT NULL,
    "Category" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL,
    "XpPerUnit" integer NOT NULL,
    "XpBonusForGoal" integer NOT NULL,
    "Period" integer NOT NULL,
    "TargetTime" time without time zone,
    "ReminderTime" time without time zone,
    "IsArchived" boolean NOT NULL,
    "ArchivedAt" timestamp with time zone,
    "Notes" character varying(1000),
    "ConcurrencyToken" uuid NOT NULL,
    "CustomCategoryName" character varying(100),
    "Unit" integer NOT NULL,
    CONSTRAINT "PK_Habits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Habits_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "NotificationPreferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "DisabledTypes" text NOT NULL,
    "QuietHoursStart" time without time zone,
    "QuietHoursEnd" time without time zone,
    "DigestEnabled" boolean NOT NULL,
    "DigestHourUtc" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificationPreferences_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Pets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Type" text NOT NULL,
    "ClientRequestId" character varying(100),
    "Level" integer NOT NULL,
    "Xp" integer NOT NULL,
    "Mood" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Nickname" text,
    "Stage" integer NOT NULL,
    "HatchedAt" timestamp with time zone,
    "EquippedAccessory" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_Pets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "IpAddress" text,
    "UserAgent" text,
    "UserId" text NOT NULL,
    "FamilyId" uuid NOT NULL,
    "ReplacedByTokenHash" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserBackgroundUnlocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Background" text NOT NULL,
    "UnlockedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_UserBackgroundUnlocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserBackgroundUnlocks_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "HabitId" integer,
    "IsRead" boolean NOT NULL,
    "DedupKey" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserNotifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserBadges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "BadgeId" integer NOT NULL,
    "EarnedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_UserBadges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserBadges_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BookReadingLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "ReadDate" timestamp with time zone NOT NULL,
    "Amount" integer NOT NULL,
    "PageReachedAt" integer,
    "XpEarned" integer NOT NULL,
    "ClientRequestId" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_BookReadingLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookReadingLogs_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);


CREATE TABLE "HabitCompletions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HabitId" integer NOT NULL,
    "CompletionDate" timestamp with time zone NOT NULL,
    "Amount" integer NOT NULL,
    "XpEarned" integer NOT NULL,
    "PetStreakBonusXp" integer NOT NULL,
    "IsOnTime" boolean NOT NULL,
    "ClientRequestId" text,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_HabitCompletions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HabitCompletions_Habits_HabitId" FOREIGN KEY ("HabitId") REFERENCES "Habits" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PetAccessoryUnlocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PetId" integer NOT NULL,
    "Accessory" text NOT NULL,
    "UnlockedAt" timestamp with time zone NOT NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_PetAccessoryUnlocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PetAccessoryUnlocks_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES "Pets" ("Id") ON DELETE CASCADE
);


INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (1, 'FIRST_COMPLETION', 'İlk alışkanlık kaydını oluşturdun.', 'İlk adım');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (2, 'STREAK_3', 'Aynı alışkanlıkta 3 dönem üst üste hedefi tutturdun.', '3''lük seri');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (3, 'STREAK_7', 'Aynı alışkanlıkta 7 dönem üst üste hedefi tutturdun.', 'Haftalık zincir');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (4, 'STREAK_30', 'Aynı alışkanlıkta 30 dönem üst üste hedefi tutturdun.', 'Aylık zincir');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (5, 'READING_STREAK_7', 'Okuma alışkanlığını 7 dönem üst üste sürdürdün.', 'Kitap kurdu');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (6, 'WATER_GROWTH_5', 'Su çiçeğin 5. seviyeye ulaştı.', 'Fidancık');
INSERT INTO "Badges" ("Id", "Code", "Description", "Name")
VALUES (7, 'WATER_GROWTH_10', 'Su çiçeğin 10. seviyeye ulaştı.', 'Çiçek bahçesi');


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE UNIQUE INDEX "IX_Badges_Code" ON "Badges" ("Code");


CREATE UNIQUE INDEX "IX_BookReadingLogs_BookId_ClientRequestId" ON "BookReadingLogs" ("BookId", "ClientRequestId") WHERE "ClientRequestId" IS NOT NULL;


CREATE INDEX "IX_BookReadingLogs_BookId_ReadDate" ON "BookReadingLogs" ("BookId", "ReadDate");


CREATE INDEX "IX_BookReadingLogs_ReadDate" ON "BookReadingLogs" ("ReadDate");


CREATE INDEX "IX_Books_CreatedAt" ON "Books" ("CreatedAt");


CREATE INDEX "IX_Books_UserId" ON "Books" ("UserId");


CREATE UNIQUE INDEX "IX_Books_UserId_ClientRequestId" ON "Books" ("UserId", "ClientRequestId") WHERE "ClientRequestId" IS NOT NULL;


CREATE INDEX "IX_Books_UserId_IsArchived" ON "Books" ("UserId", "IsArchived");


CREATE UNIQUE INDEX "IX_Books_UserId_NormalizedTitle" ON "Books" ("UserId", "NormalizedTitle") WHERE "IsArchived" = FALSE;


CREATE UNIQUE INDEX "IX_DeviceTokens_UserId_Token" ON "DeviceTokens" ("UserId", "Token");


CREATE INDEX "IX_EmailOutboxItems_Status_NextAttemptAt_CreatedAt" ON "EmailOutboxItems" ("Status", "NextAttemptAt", "CreatedAt");


CREATE UNIQUE INDEX "IX_Flowers_UserId" ON "Flowers" ("UserId");


CREATE INDEX "IX_HabitCompletions_CompletionDate" ON "HabitCompletions" ("CompletionDate");


CREATE UNIQUE INDEX "IX_HabitCompletions_HabitId_ClientRequestId" ON "HabitCompletions" ("HabitId", "ClientRequestId") WHERE "ClientRequestId" IS NOT NULL;


CREATE INDEX "IX_HabitCompletions_HabitId_CompletionDate" ON "HabitCompletions" ("HabitId", "CompletionDate");


CREATE UNIQUE INDEX "IX_Habits_UserId_ClientRequestId" ON "Habits" ("UserId", "ClientRequestId") WHERE "ClientRequestId" IS NOT NULL;


CREATE INDEX "IX_Habits_UserId_IsArchived" ON "Habits" ("UserId", "IsArchived");


CREATE UNIQUE INDEX "IX_Habits_UserId_NormalizedName" ON "Habits" ("UserId", "NormalizedName") WHERE "IsArchived" = FALSE;


CREATE UNIQUE INDEX "IX_NotificationPreferences_UserId" ON "NotificationPreferences" ("UserId");


CREATE UNIQUE INDEX "IX_PetAccessoryUnlocks_PetId_Accessory" ON "PetAccessoryUnlocks" ("PetId", "Accessory");


CREATE INDEX "IX_Pets_CreatedAt" ON "Pets" ("CreatedAt");


CREATE UNIQUE INDEX "IX_Pets_UserId_ClientRequestId" ON "Pets" ("UserId", "ClientRequestId") WHERE "ClientRequestId" IS NOT NULL;


CREATE INDEX "IX_PushOutboxItems_Status_NextAttemptAt_CreatedAt" ON "PushOutboxItems" ("Status", "NextAttemptAt", "CreatedAt");


CREATE INDEX "IX_RecalculationOutboxItems_Status_NextAttemptAt_CreatedAt" ON "RecalculationOutboxItems" ("Status", "NextAttemptAt", "CreatedAt");


CREATE INDEX "IX_RefreshTokens_FamilyId" ON "RefreshTokens" ("FamilyId");


CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE UNIQUE INDEX "IX_UserBackgroundUnlocks_UserId_Background" ON "UserBackgroundUnlocks" ("UserId", "Background");


CREATE INDEX "IX_UserBadges_BadgeId" ON "UserBadges" ("BadgeId");


CREATE UNIQUE INDEX "IX_UserBadges_UserId_BadgeId" ON "UserBadges" ("UserId", "BadgeId");


CREATE UNIQUE INDEX "IX_UserNotifications_DedupKey" ON "UserNotifications" ("DedupKey");


CREATE INDEX "IX_UserNotifications_UserId_CreatedAt" ON "UserNotifications" ("UserId", "CreatedAt");


SELECT setval(
    pg_get_serial_sequence('"Badges"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Badges") + 1,
        nextval(pg_get_serial_sequence('"Badges"', 'Id'))),
    false);


